name: Tests

on:
  pull_request:
    branches:
      - next
  workflow_dispatch:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    name: ${{ matrix.os }} Tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Install dependencies
        run: |
          go get -v -t ./...
          go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run tests
        run: go test -v ./...

      - name: Run vet
        run: go vet ./...

      - name: Run staticcheck
        run: staticcheck ./...

